### ISSUE TITLE
Doesnt always respect aspect ratio

### ISSUE THREAD

**Issue by insomniacc** [EvotecIT/ImagePlayground#11]
Hey! Awesome module btw.
I was looking for a way to resize images on linux and this fit the bill, not many cross platform options out there.

I did notice though, that aspect ratio isnt always honored.
For example, if I resize by the dominant dimension it seems fine, otherwise it isnt:
![aspectratio_bug](https://github.com/EvotecIT/ImagePlayground/assets/10046621/81eb9617-e823-4636-bbe7-81ea7c5f40b5)

I did notice that some of my images show this in the metadata:

```
HorizontalResolution : 1
VerticalResolution   : 1
ResolutionUnits      : AspectRatio
ExifProfile          : SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile
XmpProfile           : 
IccProfile           : SixLabors.ImageSharp.Metadata.Profiles.Icc.IccProfile
IptcProfile          : 
```
I'm assuming you use the metadata from the image itself to calculate the aspect ratio, and that's why I'm seeing this behaviour?
Anyway, I managed to workaround this for now with the following, but it would be nice to get this incorporated into the module:

```powershell
$ratioX = 600 / $imagefile.Width
$ratioY = 800 / $imagefile.Height
$ratio = $ratioY
if($ratioX -le $ratioY){
    $ratio = $ratioX
}
$NewHeight = $imagefile.Height*$ratio
$NewWidth  = $imagefile.Width*$ratio
Resize-Image -FilePath $imagefile.FilePath -OutputPath "C:\temp\test\test.jpg" -Height $NewHeight -Width $NewWidth
```

**Comment by PrzemyslawKlys** [comment]
This code is located at:

https://github.com/EvotecIT/ImagePlayground/blob/d64aa65353fa2b4adbfad7895e8a8758dc9a4ab7/Sources/ImagePlayground/ImageHelper.cs#L60-L92

And then in PS

https://github.com/EvotecIT/ImagePlayground/blob/d64aa65353fa2b4adbfad7895e8a8758dc9a4ab7/Public/Resize-Image.ps1#L61-L81

The logic for width, but no height is:
```cs
var newWidth = width.Value;
var newHeight = (image.Height / image.Width) * newWidth;
image.Mutate(x => x.Resize(newWidth, newHeight));
```

The logic for height, but no width is:

```cs
var newHeight = height.Value;
var newWidth = (image.Width / image.Height) * newHeight;
image.Mutate(x => x.Resize(newWidth, newHeight));
```

Could be that Iam counting this wrong ;)

**Comment by Abax378** [comment]
When calling Resize-Image like this where input.jpg is 800 x 450 (width x height) . . . 

Resize-Image -FilePath "C:\temp\input.jpg" -OutputPath "C\temp\output.jpg" -Height 225

. . . the resulting image is 225 x 225. The function incorrectly sets both sides to 225 instead of outputting a proportional image at 400 x 225.

The problem appears to be fixable in this line of code from the function Resize-Image in ImagePlayground.psm1:
    **[ImagePlayground.ImageHelper]::Resize($FilePath, $OutputPath, $null, $height)**
Changing $null to 0 causes the function to work as expected:
    **[ImagePlayground.ImageHelper]::Resize($FilePath, $OutputPath, 0, $height)**

I presume the logic is happening inside a .dll, so I don't know why 0 for width works when $null for width was intended to trigger a proportion calculation. Maybe it's related to uninitialized variables?

My environment is
Name                                     Value
----                                         -----
PSVersion                               7.4.0
PSEdition                                Core
GitCommitId                           7.4.0
OS                                           Microsoft Windows 10.0.19045
Platform                                  Win32NT
PSCompatibleVersions		{1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion	2.3
SerializationVersion                1.1.0.1
WSManStackVersion		3.0

**Comment by PrzemyslawKlys** [comment]
I'll fix it. As mentioned in the email i have logic inside it for null which is not necessary and it's better to provide 0 directly to DLL ImageSharp.

**Comment by Abax378** [comment]
> I'll fix it. As mentioned in the email i have logic inside it for null which is not necessary and it's better to provide 0 directly to DLL ImageSharp.

Thanks for such a quick reply!
